openapi: 3.1.0
info:
  title: API de Autenticación y Productos
  description: API para autenticar usuarios y gestionar productos.
  version: 1.0.0
paths:
  /api/auth:
    post:
      summary: Autenticar usuario
      description: Endpoint para autenticar un usuario mediante username y password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: Autenticación exitosa.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  token:
                    type: string
        '401':
          description: Credenciales inválidas.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /api/products:
    get:
      summary: Listar productos
      description: Obtiene una lista de productos disponibles.
      responses:
        '200':
          description: Lista de productos.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
        '401':
          description: No autorizado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    post:
      summary: Crear producto
      description: Crea un nuevo producto de manera asíncrona.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
      responses:
        '202':
          description: Creación en progreso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '422':
          description: Error de validación.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '401':
          description: No autorizado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
